name: "🐞 Bug"
description: "🐞 Bug"
title: "<title>"
labels:
  - "Bug"
  - "good first issue"
  - "help wanted"
  - "up-for-grabs"

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report:

  - type: input
    attributes:
      label: "Description: (Clear/concise. Screenshot/Video welcome to upload below)"
    validations:
      required: true

  - type: input
    attributes:
      label: "Steps to reproduce: (Might only happen with a certain feature of ours enabled?)"
    validations:
      required: true

  - type: input
    attributes:
      label: "Since when? Or when YouTube changed something? Or through our update?"
      placeholder: (Date / Reason / Version)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Browser:"
      options:
        - label: "Chrome"
          value: "Chrome"
        - label: "Firefox"
          value: "Firefox"
        - label: "Safari"
          value: "Safari"
        - label: "Edge"
          value: "Edge"
        - label: "Brave"
          value: "Brave"
        - label: "Vivaldi"
          value: "Vivaldi"
        - label: "Opera"
          value: "Opera"
        - label: "Opera GX"
          value: "Opera GX"
    validations:
      required: false

  - type: input
    attributes:
      label: "Other Browser/s:"
    validations:
      required: false

  - type: input
    attributes:
      label: "Are any errors shown in the Browser-Console? "
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        (`F12`-key, then `console`-tab. Try without other extensions)

  - type: markdown
    attributes:
      value: |
        ### Before submitting:
        Thanks for coming & caring! 
        Sometimes even 3 words are enough for a bug report. 
        Just please check if the issue has already been reported. If so, you can add different/better words to that report.
        [GitHub's issue search](https://github.com/ImprovedTube/ImprovedTube/issues?q=) _(use the link or remove "is:issue is:open" from the search)_
        (If it was posted before, you can answer/react there to give it your voice and this also move it up in our lists) 
        If the status is "closed" (=fixed) recently, then the Browser's stores can be updated soon. If it was already closed months or years ago, then it might have appeared again and must be fixed again.)

  - type: checkboxes
    attributes:
      label: "Tested as only active extension (incognito mode or another browser users):"
      options:
        - label: "Yes"
        - label: "No"

  - type: input
    attributes:
      label: "Expected preferred behavior:"
    validations:
      required: false

  - type: input
    attributes:
      label: "ImprovedTube Version"
      description: "(Written in the Extension header & your Browser's store)"
    validations:
      required: false

  - type: input
    attributes:
      label: "Your Settings (From the Extension's `⋮`-Hamburger menu > Settings > Backup & reset > Export settings)"
    validations:
      required: false      
     - type: markdown
       attributes:
       value: |
          You can remove Blocklist, History Analyzer data - or paste the following in the Browser-Console and hit enter: 
          `(function({analyzer, blocklist, ...a}){return JSON.stringify(a)})(ImprovedTube.storage)`
          
  - type: input
    attributes:
      label: "your YouTube Document"
    validations:
    - type: markdown
      attributes:
        value: |
          (`F12` copy the whole root element: \<html> (alternative: CTRL+U) [Test](https://github.com/code-charity/youtube/wiki/Contributing#Test)

  - type: input
    attributes:
      label: "OS / Device:
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <!-- Many thanks & smiles! -->
