name: "🐞 Bug"
description: "🐞 Bug"
title: "<title>"
labels:
  - "Bug"
  - "good first issue"
  - "help wanted"
  - "up-for-grabs"

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report:

  - type: textarea
    attributes:
      label: "**Description:**"
      description: _(Clear/concise. Screenshot/Video welcome)_
    validations:
      required: true

  - type: textarea
    attributes:
      label: "**Steps to reproduce this:**"
      description: _(Might only happen with a certain feature of ours enabled?)_
    validations:
      required: true

  - type: input
    attributes:
      label: "**Since when?:**"
      description: Or when YouTube changed something? Through our update?
      placeholder: Enter date or version
    validations:
      required: true

  - type: dropdown  # Corrected from 'select' to 'dropdown'
    attributes:
      label: "**Browser:**"
      options:
        - label: "Chrome"
          value: Chrome
        - label: "Firefox"
          value: Firefox
        - label: "Safari"
          value: Safari
        - label: "Edge"
          value: Edge
        - label: "Brave"
          value: Brave
        - label: "Vivaldi"
          value: Vivaldi
        - label: "Opera"
          value: Opera
        - label: "Opera GX"
          value: Opera GX
    validations:
      required: false

  - type: input
    attributes:
      label: "**Other Browser/s:**"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "**Are any errors shown in the Browser-Console?:**"
      description: _(`F12`-key, then `console`-tab. Try without other extensions)_
    validations:
      required: true

  - type: markdown  # Removed 'conditional' as it's not a valid input type
    attributes:
      value: |
        ### Before submitting:
        Thanks for coming & caring! 
        Sometimes even 3 words are enough for a bug report. 
        Just please check if the issue has already been reported. If so, you can add different/better words to that report.
        [GitHub's issue search](https://github.com/ImprovedTube/ImprovedTube/issues?q=) _(use the link or remove "is:issue is:open" from the search)_
        (If it was posted before, you can answer/react there to give it your voice and this also move it up in our lists) 
        If the status is "closed" (=fixed) recently, then the Browser's stores can be updated soon. If it was already closed months or years ago, then it might have appeared again and must be fixed again.)

  - type: checkboxes
    attributes:
      label: "**Tested as only active extension (incognito mode or another browser users):**"
      options:
        - label: Yes
        - label: No

  - type: textarea
    attributes:
      label: "**Expected preferred behavior:**"
    validations:
      required: false

  - type: input
    attributes:
      label: "**ImprovedTube Version (Written in the Extension header & your Browser's store)**"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "**Your Settings (From the Extension's `⋮`-Hamburger menu > Settings > Backup & reset > Export settings**"
      description: |-
        You can remove any Blocklist, History Analyzer data - or paste the following in the Browser-Console and hit enter: 
        `(function({analyzer, blocklist, ...a}){return JSON.stringify(a)})(ImprovedTube.storage)`
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### YouTube-Document:
        (`F12` copy the whole root element: \<html> (alternative: CTRL+U) [Test](https://github.com/code-charity/youtube/wiki/Contributing#Test)

  - type: input
    attributes:
      label: "**OS / Device:**"
      description: (Enter your operating system and device details)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <!-- Many thanks & smiles! -->
